name: CI ReOrder

on:
  push:
    branches: [ dev, master, release ]
  pull_request:
    branches: [ dev, master, release ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Iniciar la aplicación Spring Boot en segundo plano (necesario para Karate)
      - name: Iniciar aplicación Spring Boot
        run: mvn spring-boot:start &
        # '&' al final ejecuta el proceso en segundo plano

      # Ejecutar tests (incluyendo Karate)
      - name: Ejecutar tests
        run: mvn -B verify

      # Detener la aplicación
      - name: Detener aplicación
        if: always()
        run: mvn spring-boot:stop

      # Subir artefactos
      - name: Subir JAR
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar
