name: CI ReOrder

on:
  push:
    branches: [ dev, master, release ]
  pull_request:
    branches: [ dev, master, release ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout código
        uses: actions/checkout@v4

      # 2. Configurar Java (ej: Java 21 para Spring Boot 3.x)
      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Construir y ejecutar tests con Maven
      - name: Build y tests
        run: mvn -B verify

      # 4. Subir artefactos (JAR)
      - name: Subir JAR
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar
